# Generated by Django 3.2.3 on 2021-06-03 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(default='', max_length=20)),
                ('product', models.CharField(default='', max_length=30)),
                ('price', models.CharField(default='', max_length=60)),
                ('qty', models.CharField(default='', max_length=90)),
            ],
        ),
        migrations.DeleteModel(
            name='Details',
        ),
    ]
