# Generated by Django 3.2.3 on 2021-06-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20210604_0307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer', models.CharField(default='', max_length=20)),
                ('Product', models.CharField(default='', max_length=30)),
                ('Price', models.CharField(default='', max_length=60)),
                ('Qty', models.CharField(default='', max_length=90)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
